# Welcome to Jekyll!

# Website settings
title: OpenMeteor
description: OpenMeteor's blog,use Jekyll and github pages.
keywords: blog,Jekyll,github,gh-pages
baseurl:  / # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: https://openmeteor.github.io  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before
logo: /static/assets/img/landing/brand-background.png

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: OpenMeteor  # Be used at blog posts' author.
  first_name:   # Be used at index page about me section.
  last_name:   # Be used at index page about me section.
  avatar: /static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
  github_username: openmeteor  # Leave blank if you don't have now
  linkedin_id:  # Leave blank if you don't have now
  facebook_username:   # Leave blank if you don't have now
  twitter_username:  # Leave blank if you don't have now
  email:   # Leave blank if you don't have now
  cv: # An online CV can be printed as PDF, leave blank if you don't have now

# members -- index page "about me" section
  member1:  # change following line to your infomation.
    name: Jeremie  # Be used at blog posts' author.
    first_name: Jeremie # Be used at index page about me section.
    last_name: Vaubaillon  # Be used at index page about me section.
    avatar: /static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
    github_username:  # Leave blank if you don't have now
    linkedin_id:  # Leave blank if you don't have now
    facebook_username:   # Leave blank if you don't have now
    twitter_username:  # Leave blank if you don't have now
    email:   # Leave blank if you don't have now
    cv: # An online CV can be printed as PDF, leave blank if you don't have now
  member2:  # change following line to your infomation.
    name: Daniel  # Be used at blog posts' author.
    first_name: Daniel # Be used at index page about me section.
    last_name: Kastinen  # Be used at index page about me section.
    avatar: /static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
    github_username:  # Leave blank if you don't have now
    linkedin_id:  # Leave blank if you don't have now
    facebook_username:   # Leave blank if you don't have now
    twitter_username:  # Leave blank if you don't have now
    email:   # Leave blank if you don't have now
    cv: # An online CV can be printed as PDF, leave blank if you don't have now
  member3:  # change following line to your infomation.
    name: Hadrien  # Be used at blog posts' author.
    first_name: Hadrien # Be used at index page about me section.
    last_name: Devillepoix  # Be used at index page about me section.
    avatar: /static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
    github_username:  # Leave blank if you don't have now
    linkedin_id:  # Leave blank if you don't have now
    facebook_username:   # Leave blank if you don't have now
    twitter_username:  # Leave blank if you don't have now
    email:   # Leave blank if you don't have now
    cv: # An online CV can be printed as PDF, leave blank if you don't have now
  member3:  # change following line to your infomation.
    name: Denis  # Be used at blog posts' author.
    first_name: Denis # Be used at index page about me section.
    last_name: Vida  # Be used at index page about me section.
    avatar: /static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
    github_username: dvida # Leave blank if you don't have now
    linkedin_id:  # Leave blank if you don't have now
    facebook_username:   # Leave blank if you don't have now
    twitter_username:  # Leave blank if you don't have now
    email: dvida@uwo.ca  # Leave blank if you don't have now
    cv: # An online CV can be printed as PDF, leave blank if you don't have now

# skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: icon-apache
    - name: fa-linux
  skill_icon2:
    - name: fa-linux
    - name: icon-apache
  desc: Add Openmeteor description.  # Describe yourself.

# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  # name: jalpc

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  # id:

## google optimize
go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: on  # index page carousel switch
blog_carousel: on  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

